/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
    /* Loop forever */
	/*
	 * uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;
	*/

	RCC_AHB1ENR_t volatile * const pClkCtrlReg = (RCC_AHB1ENR_t *)0x40023830;
	pClkCtrlReg -> gpioden = 1;

	GPIOx_MODER_t volatile  * const pPortDModeReg = (GPIOx_MODER_t *)0x40020C00;
	pPortDModeReg -> pin_12 = 1;

	GPIOx_ODR_t volatile * const pd12 = (GPIOx_ODR_t *)0x40020C14;

	while(1){
		pd12 ->odr12 = 1;

		for(uint32_t i = 0;i<300000;i++);

//		GPIOx_ODR_t *pd12 = (GPIOx_ODR_t *)0x40020C14;
		pd12 ->odr12 = 0;

		for(uint32_t i = 0;i<300000;i++);

	}

//	GPIOx_ODR_t *pd12 = (GPIOx_ODR_t *)0x40020C14;
//	pd12 ->odr12 = 1;

//	for(;;);
}
